name: Deploy
on:
  repository_dispach:
    inputs:
      name: 
      required: true
      type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Imprime nome
        run: echo "Nome ${{ inputs.name }}"

