on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_deploy }}
    steps:
      - name: Imprime Nome
        run: echo "Nome do cidadão: ${{ inputs.name }}"